version: '3.8'

networks:
  ewb-net:
    driver: bridge

services:
  restapi:
    build: ./restapi
    container_name: ewb-restapi
    ports:
      - 80:80
    environment:
      SOLR_URL: http://solr:8983
    depends_on:
      - solr
    networks:
      - ewb-net
  solr:
    image: solr:latest
    container_name: ewb-solr
    restart: always
    volumes:
      - ./db/data/solr:/var/solr
      #- ./logs/solr:/opt/solr/server/logs
      #-./contrib/jscustomsimilarity:/opt/solr/contrib/jscustomsimilarity --> para copiar plugin semejanza
      - ./data:/opt/solr/server/solr
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -Djute.maxbuffer=0x5000000"
    networks:
      - ewb-net
    #command: bin/solr zk upconfig -zkhost zoo:2181 -n ewb_config -d /opt/solr-9.1.1/server/solr/configsets/ewb_config

  zoo:
    image: zookeeper
    container_name: ewb-zoo
    restart: always
    ports:
      - 2180:8080
      - 2181:2181
    environment:
      - JVMFLAGS=-Djute.maxbuffer=50000000
    volumes:
      - ./db/data/zoo/data:/data
      - ./db/data/zoo/logs:/datalog
    networks:
      - ewb-net