version: "3.8"

networks:
  ewb-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.128.0/24

services:
  restapi:
    build: ./ewb-tm
    container_name: ewb-tm
    ports:
      - 82:82
    environment:
      SOLR_URL: http://solr:8983
      INFERENCE_URL: http://ewb-inferencer:90
    depends_on:
      - solr
      - inferencer
    networks:
      - ewb-net 
    volumes:
      - ./data/source:/data/source
      - ./data/inference:/data/inference
      - ./ewb_config:/config
  
  inferencer:
    build: ./ewb-inferencer
    container_name: ewb-inferencer
    ports:
      - 90:90
    networks:
      - ewb-net
    volumes:
      - ./data/source:/data/source
      - ./data/inference:/data/inference
      - ./ewb_config:/config

  classifier:
    build: ./ewb-classifier
    container_name: ewb-classifier
    ports:
      - 100:100
    networks:
      - ewb-net
    volumes:
      - ./data/classifier:/data/classifier
      - ./ewb_config:/config
   
  initializer:
    image: alpine
    container_name: ewb-solr-initializer
    restart: "no"
    entrypoint: |
      /bin/sh -c "chown 8983:8983 /solr"
    volumes:
      - ./db/data/solr:/solr

  solr:
    image: solr:9.1.1
    container_name: ewb-solr
    restart: always
    volumes:
      - ./db/data/solr:/var/solr
      - ./solr_plugins/solr-ewb-jensen-shanon-distance-plugin/solr-js-plugin/target/solr-js-plugin-1.0.0.jar:/opt/solr/dist/plugins/solr-js-plugin-1.0.0.jar
      - ./solr_plugins/solr-ewb-sims/solr-sims-plugin/target/solr-sims-plugin-1.0.0.jar:/opt/solr/dist/plugins/solr-sims-plugin-1.0.0.jar
      - ./solr_config:/opt/solr/server/solr
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 -Djute.maxbuffer=0x5000000"
    networks:
      - ewb-net

  zoo:
    image: zookeeper
    container_name: ewb-zoo
    restart: always
    ports:
      - 2180:8080
      - 2181:2181
    environment:
      - JVMFLAGS=-Djute.maxbuffer=50000000
    volumes:
      - ./db/data/zoo/data:/data
      - ./db/data/zoo/logs:/datalog
    networks:
      - ewb-net

  solr-config:
    build: ./solr_config
    container_name: ewb-solr_config
    ports:
      - 81:81
    depends_on:
      - solr
      - zoo
    networks:
      - ewb-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./solr_config/bash_scripts:/bash_scripts
      - ./db/data/solr:/db/data/solr
    command: 
      - sh
      - -c
      - 'chmod +x /bash_scripts/init_config.sh && ls /bash_scripts && bash_scripts/init_config.sh /db/data/solr/data'
